# Generated by Django 5.1.1 on 2025-04-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0005_jobacceptance_salary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobacceptance',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobacceptance',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_offers', to='placement_api.offers'),
        ),
    ]
