# Generated by Django 5.1.1 on 2025-04-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0006_remove_jobacceptance_salary_jobacceptance_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobacceptance',
            name='offer',
        ),
        migrations.AddField(
            model_name='jobacceptance',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
