# Generated by Django 5.1.1 on 2025-05-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0007_remove_jobacceptance_offer_jobacceptance_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobacceptance',
            name='company_name',
        ),
    ]
