# Generated by Django 5.1.1 on 2025-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0008_remove_jobacceptance_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobacceptance',
            name='is_reg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobacceptance',
            name='is_sel',
            field=models.BooleanField(default=False),
        ),
    ]
