# Generated by Django 5.1.1 on 2025-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0009_jobacceptance_is_reg_jobacceptance_is_sel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='degree',
            field=models.CharField(choices=[('BE', 'BE'), ('ME', 'ME')], default='BE', max_length=10),
        ),
    ]
