# Generated by Django 5.1.1 on 2025-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0010_offers_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='is_ojt_aedp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='degree',
            field=models.CharField(choices=[('BE', 'BE'), ('ME', 'ME'), ('BE, ME', 'BE, ME')], default='BE', max_length=10),
        ),
    ]
