export const data2022 = {
  "2022": [
    {
      "Placement Statistics ": "COMP",
      "Total Offers": 167,
      "Total Single Offers (On Campus)": 92,
      "Off-Campus Offers": 3,
      "Cumulative Figures (On+Off Campus) out of Intrested": 95,
      "Cumulative Figures (On+Off Campus) out of Eligible": 95,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 154,
      "Students Opted for Higher Studies": 53,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 101,
      "Students Eligible for Placement": 100,
      "Students Not-Eligible for Placement": 1,
      "% Interested in Placement": 0.9405940594059405,
      "% Eligible for Placement": 0.95,
      "% Not-Eligible for Placement": 0,
      "No of Super Dream/Dream": 84,
      "Maximum Salary( INR- LPA)": 30,
      "Minimum Salary ( INR- LPA)": 3.25,
      "Average Salary ( INR- LPA)": 6.662365591397848,
      "Median Salary (INR-LPA)": 6,
      "No of Companies Visited": 191,
    },
    {
      "Placement Statistics ": "ELEX",
      "Total Offers": 59,
      "Total Single Offers (On Campus)": 40,
      "Off-Campus Offers": 6,
      "Cumulative Figures (On+Off Campus) out of Intrested": 46,
      "Cumulative Figures (On+Off Campus) out of Eligible": 46,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 73,
      "Students Opted for Higher Studies": 14,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 58,
      "Students Eligible for Placement": 58,
      "Students Not-Eligible for Placement": 0,
      "% Interested in Placement": 0.7931034482758621,
      "% Eligible for Placement": 0.7931034482758621,
      "% Not-Eligible for Placement": 0,
      "No of Super Dream/Dream": 10,
      "Maximum Salary( INR- LPA)": 9,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.481627906976745,
      "Median Salary (INR-LPA)": 4,
      "No of Companies Visited": 180,
    },
    {
      "Placement Statistics ": "E&TC",
      "Total Offers": 127,
      "Total Single Offers (On Campus)": 89,
      "Off-Campus Offers": 12,
      "Cumulative Figures (On+Off Campus) out of Intrested": 101,
      "Cumulative Figures (On+Off Campus) out of Eligible": 101,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 147,
      "Students Opted for Higher Studies": 41,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 106,
      "Students Eligible for Placement": 105,
      "Students Not-Eligible for Placement": 1,
      "% Interested in Placement": 0.9528301886792453,
      "% Eligible for Placement": 0.9619047619047619,
      "% Not-Eligible for Placement": 0,
      "No of Super Dream/Dream": 34,
      "Maximum Salary( INR- LPA)": 8.23,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.74451612903226,
      "Median Salary (INR-LPA)": 4.5,
      "No of Companies Visited": 180,
    },
    {
      "Placement Statistics ": "IT",
      "Total Offers": 157,
      "Total Single Offers (On Campus)": 83,
      "Off-Campus Offers": 5,
      "Cumulative Figures (On+Off Campus) out of Intrested": 88,
      "Cumulative Figures (On+Off Campus) out of Eligible": 88,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 140,
      "Students Opted for Higher Studies": 46,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 91,
      "Students Eligible for Placement": 90,
      "Students Not-Eligible for Placement": 1,
      "% Interested in Placement": 0.967032967032967,
      "% Eligible for Placement": 0.9777777777777777,
      "% Not-Eligible for Placement": 0,
      "No of Super Dream/Dream": 70,
      "Maximum Salary( INR- LPA)": 14,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 6.222558139534883,
      "Median Salary (INR-LPA)": 5.25,
      "No of Companies Visited": 191,
    },
    {
      "Placement Statistics ": "Mech",
      "Total Offers": 60,
      "Total Single Offers (On Campus)": 45,
      "Off-Campus Offers": 23,
      "Cumulative Figures (On+Off Campus) out of Intrested": 68,
      "Cumulative Figures (On+Off Campus) out of Eligible": 68,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 139,
      "Students Opted for Higher Studies": 63,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 76,
      "Students Eligible for Placement": 76,
      "Students Not-Eligible for Placement": 0,
      "% Interested in Placement": 0.8947368421052632,
      "% Eligible for Placement": 0.8947368421052632,
      "% Not-Eligible for Placement": 0,
      "No of Super Dream/Dream": 6,
      "Maximum Salary( INR- LPA)": 7,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.201621621621623,
      "Median Salary (INR-LPA)": 4,
      "No of Companies Visited": 129,
    },
    {
      "Placement Statistics ": "CIVIL",
      "Total Offers": 32,
      "Total Single Offers (On Campus)": 29,
      "Off-Campus Offers": 31,
      "Cumulative Figures (On+Off Campus) out of Intrested": 60,
      "Cumulative Figures (On+Off Campus) out of Eligible": 59,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 1,
      "Students Admitted in Final Year": 151,
      "Students Opted for Higher Studies": 60,
      "Students Opted for  Entrepreneur": 11,
      "Students Interested in Placement": 80,
      "Students Eligible for Placement": 80,
      "Students Not-Eligible for Placement": 0,
      "% Interested in Placement": 0.75,
      "% Eligible for Placement": 0.7375,
      "% Not-Eligible for Placement": 0,
      "No of Super Dream/Dream": 0,
      "Maximum Salary( INR- LPA)": 4.5,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 3.758095238095238,
      "Median Salary (INR-LPA)": 4,
      "No of Companies Visited": 109,
    },
    {
      "Placement Statistics ": "Total ",
      "Total Offers": 602,
      "Total Single Offers (On Campus)": 378,
      "Off-Campus Offers": 80,
      "Cumulative Figures (On+Off Campus) out of Intrested": 458,
      "Cumulative Figures (On+Off Campus) out of Eligible": 457,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 1,
      "Students Admitted in Final Year": 804,
      "Students Opted for Higher Studies": 277,
      "Students Opted for  Entrepreneur": 15,
      "Students Interested in Placement": 512,
      "Students Eligible for Placement": 509,
      "Students Not-Eligible for Placement": 3,
      "% Interested in Placement": 0.89453125,
      "% Eligible for Placement": 0.8978388998035364,
      "% Not-Eligible for Placement": 0.3333333333333333,
      "No of Super Dream/Dream": 204,
      "Maximum Salary( INR- LPA)": 30,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.423780160857905,
      "Median Salary (INR-LPA)": 4.5,
      "No of Companies Visited": 245,
    },
  ],
};
