# Generated by Django 5.1.1 on 2025-09-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=50)),
                ('min_tenth_marks', models.CharField(max_length=10)),
                ('min_higher_secondary_marks', models.CharField(max_length=10)),
                ('min_cgpa', models.CharField(max_length=10)),
                ('accepted_kt', models.BooleanField(default=False)),
                ('domain', models.CharField(max_length=100)),
                ('departments', models.CharField(max_length=255)),
                ('is_aedp_or_pli', models.BooleanField(default=False)),
                ('is_aedp_or_ojt', models.BooleanField(default=False)),
                ('selected_departments', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('intro', models.TextField()),
                ('about', models.TextField()),
                ('company_registration_link', models.URLField()),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='staff.companyregistration')),
            ],
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='notice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.notice'),
        ),
        migrations.AddConstraint(
            model_name='companyregistration',
            constraint=models.UniqueConstraint(fields=('name', 'batch'), name='unique_name_batch'),
        ),
    ]
