# Generated by Django 5.1.1 on 2024-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('late', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('present', models.IntegerField()),
                ('program_name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('uid', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], default='SEMESTER 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('num_sessions', models.IntegerField()),
                ('num_days', models.IntegerField()),
                ('dates', models.JSONField()),
                ('file_headers', models.JSONField(default=list)),
                ('student_data', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Program1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_Div', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('training_attendance', models.FloatField()),
                ('training_performance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleAttendanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('present', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BatchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('total_students', models.IntegerField()),
                ('total_present', models.IntegerField()),
                ('total_absent', models.IntegerField()),
                ('total_late', models.IntegerField()),
                ('program_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('batch', 'session', 'program_name', 'year')},
            },
        ),
    ]
