# Generated by Django 5.1.1 on 2024-12-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='program1',
            table='program1',
        ),
    ]
