# Generated by Django 5.1.1 on 2024-12-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0002_alter_program1_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='program1',
            name='program_name',
            field=models.CharField(default='ACT_APTITUDE', max_length=100),
        ),
        migrations.AddField(
            model_name='program1',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], default='SEMESTER 1', max_length=100),
        ),
        migrations.AlterModelTable(
            name='attendancedata',
            table='attendance_data',
        ),
        migrations.AlterModelTable(
            name='attendancerecord',
            table='attendance_attendancerecord',
        ),
        migrations.AlterModelTable(
            name='batchattendance',
            table='batch_attendance',
        ),
    ]
