# Generated by Django 5.1.1 on 2024-12-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0004_attendancerecord_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedata',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancedata',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancedata',
            name='present',
            field=models.IntegerField(default=False),
        ),
    ]
