# Generated by Django 5.1.1 on 2024-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0005_attendancedata_absent_alter_attendancedata_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program1',
            name='Name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='program1',
            name='UID',
            field=models.CharField(default='20', max_length=100),
        ),
    ]
