# Generated by Django 5.1.1 on 2024-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0006_program1_name_program1_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedata',
            name='absent',
        ),
        migrations.AlterField(
            model_name='attendancedata',
            name='late',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendancedata',
            name='present',
            field=models.IntegerField(),
        ),
    ]
