# Generated by Django 5.1.1 on 2024-12-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0007_remove_attendancedata_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedata',
            name='late',
            field=models.CharField(default='Late', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancedata',
            name='present',
            field=models.CharField(default='Present', max_length=100),
        ),
    ]
