# Generated by Django 4.2.19 on 2025-10-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program_coordinator_api', '0009_attendancerecord_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('branch_div', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], max_length=100)),
                ('training_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_performance',
                'unique_together': {('uid', 'training_type', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TrainingPerformanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='program_coordinator_api.trainingperformance')),
            ],
            options={
                'db_table': 'training_performance_category',
                'unique_together': {('performance', 'category_name')},
            },
        ),
    ]
