# Generated by Django 4.2.19 on 2025-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0010_trainingperformance_trainingperformancecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingperformance',
            name='semester',
            field=models.CharField(blank=True, choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingperformance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
