# Generated by Django 5.1.1 on 2025-11-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0011_alter_trainingperformance_semester_and_more'),
        ('student', '0014_merge_20251024_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingperformance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainingperformance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingperformance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='trainingperformance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='trainingperformance',
            name='branch_div',
        ),
        migrations.RemoveField(
            model_name='trainingperformance',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trainingperformance',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='trainingperformance',
            name='year',
        ),
    ]
