# Generated by Django 5.1.1 on 2025-11-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0012_alter_trainingperformance_unique_together_and_more'),
        ('student', '0015_alter_trainingperformancesemester_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingperformance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_performance', to='student.student'),
        ),
    ]
