# Generated by Django 5.1.1 on 2026-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='documents_to_carry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='eligibility_criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='from_designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notice',
            name='from_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(default='Placement', max_length=50),
        ),
        migrations.AddField(
            model_name='notice',
            name='roles',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='skill_required',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='sr_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='walk_in_interview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='company_registration_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
