export const data2025 = {
  "2025": [
    {
      "Placement Statistics ": "AI&DS",
      "Total Offers ": 18,
      "Total Single Offers (On Campus)": 15,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 15,
      "Cumulative Figures (On+Off Campus) out of Eligible": 15,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 69,
      "Students Opted for Higher Studies": 26,
      "Students Opted for  Entrepreneur": 7,
      "Students Interested in Placement": 36,
      "Students Eligible for Placement": 36,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.4166666666666667,
      "% of Placement out of Eligible students  for Placement": 0.4166666666666667,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 4,
      "Maximum Salary( INR- LPA)": 8.29,
      "Minimum Salary ( INR- LPA)": 3.25,
      "Average Salary ( INR- LPA)": 4.909333333333333,
      "Median Salary (INR-LPA)": 4.5,
      "Mode Salary (INR-LPA)": 4.5,
      "No of Companies Visited": 69,
    },
    {
      "Placement Statistics ": "AI&ML",
      "Total Offers ": 22,
      "Total Single Offers (On Campus)": 22,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 22,
      "Cumulative Figures (On+Off Campus) out of Eligible": 22,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 68,
      "Students Opted for Higher Studies": 17,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 51,
      "Students Eligible for Placement": 51,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.4313725490196079,
      "% of Placement out of Eligible students  for Placement": 0.4313725490196079,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 6,
      "Maximum Salary( INR- LPA)": 9.5,
      "Minimum Salary ( INR- LPA)": 3.5,
      "Average Salary ( INR- LPA)": 4.965454545454545,
      "Median Salary (INR-LPA)": 4.25,
      "Mode Salary (INR-LPA)": 4.25,
      "No of Companies Visited": 69,
    },
    {
      "Placement Statistics ": "IOT",
      "Total Offers ": 13,
      "Total Single Offers (On Campus)": 9,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 10,
      "Cumulative Figures (On+Off Campus) out of Eligible": 10,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 32,
      "Students Opted for Higher Studies": 4,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 28,
      "Students Eligible for Placement": 28,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.3571428571428572,
      "% of Placement out of Eligible students  for Placement": 0.3571428571428572,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 3,
      "Maximum Salary( INR- LPA)": 40,
      "Minimum Salary ( INR- LPA)": 3.6,
      "Average Salary ( INR- LPA)": 9.321999999999997,
      "Median Salary (INR-LPA)": 4.25,
      "Mode Salary (INR-LPA)": 3.6,
      "No of Companies Visited": 69,
    },
    {
      "Placement Statistics ": "COMP",
      "Total Offers ": 107,
      "Total Single Offers (On Campus)": 90,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 91,
      "Cumulative Figures (On+Off Campus) out of Eligible": 91,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 208,
      "Students Opted for Higher Studies": 53,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 154,
      "Students Eligible for Placement": 149,
      "Students Not-Eligible for Placement": 5,
      "% of Placement out of Interested Students in Placement": 0.5909090909090909,
      "% of Placement out of Eligible students  for Placement": 0.610738255033557,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 39,
      "Maximum Salary( INR- LPA)": 20,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 6.247912087912092,
      "Median Salary (INR-LPA)": 4.5,
      "Mode Salary (INR-LPA)": 4.25,
      "No of Companies Visited": 81,
    },
    {
      "Placement Statistics ": "CS&E",
      "Total Offers ": 34,
      "Total Single Offers (On Campus)": 25,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 26,
      "Cumulative Figures (On+Off Campus) out of Eligible": 26,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 68,
      "Students Opted for Higher Studies": 7,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 58,
      "Students Eligible for Placement": 58,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.4482758620689655,
      "% of Placement out of Eligible students  for Placement": 0.4482758620689655,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 13,
      "Maximum Salary( INR- LPA)": 20,
      "Minimum Salary ( INR- LPA)": 3.6,
      "Average Salary ( INR- LPA)": 5.771923076923074,
      "Median Salary (INR-LPA)": 4.75,
      "Mode Salary (INR-LPA)": 3.6,
      "No of Companies Visited": 75,
    },
    {
      "Placement Statistics ": "E&CS",
      "Total Offers ": 19,
      "Total Single Offers (On Campus)": 18,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 18,
      "Cumulative Figures (On+Off Campus) out of Eligible": 18,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 70,
      "Students Opted for Higher Studies": 18,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 51,
      "Students Eligible for Placement": 50,
      "Students Not-Eligible for Placement": 1,
      "% of Placement out of Interested Students in Placement": 0.3529411764705883,
      "% of Placement out of Eligible students  for Placement": 0.36,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 4,
      "Maximum Salary( INR- LPA)": 5.75,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.125,
      "Median Salary (INR-LPA)": 3.925,
      "Mode Salary (INR-LPA)": 4.25,
      "No of Companies Visited": 76,
    },
    {
      "Placement Statistics ": "E&TC",
      "Total Offers ": 40,
      "Total Single Offers (On Campus)": 35,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 36,
      "Cumulative Figures (On+Off Campus) out of Eligible": 36,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 129,
      "Students Opted for Higher Studies": 38,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 90,
      "Students Eligible for Placement": 79,
      "Students Not-Eligible for Placement": 11,
      "% of Placement out of Interested Students in Placement": 0.4,
      "% of Placement out of Eligible students  for Placement": 0.4556962025316456,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 8,
      "Maximum Salary( INR- LPA)": 8.65,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.389999999999999,
      "Median Salary (INR-LPA)": 4.25,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 78,
    },
    {
      "Placement Statistics ": "IT",
      "Total Offers ": 82,
      "Total Single Offers (On Campus)": 62,
      "Off-Campus Offers": 5,
      "Cumulative Figures (On+Off Campus) out of Interested": 67,
      "Cumulative Figures (On+Off Campus) out of Eligible": 67,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 136,
      "Students Opted for Higher Studies": 18,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 118,
      "Students Eligible for Placement": 118,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.5677966101694916,
      "% of Placement out of Eligible students  for Placement": 0.5677966101694916,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 31,
      "Maximum Salary( INR- LPA)": 20,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.841060606060609,
      "Median Salary (INR-LPA)": 4.5,
      "Mode Salary (INR-LPA)": 4.25,
      "No of Companies Visited": 81,
    },
    {
      "Placement Statistics ": "Mech",
      "Total Offers ": 14,
      "Total Single Offers (On Campus)": 11,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 12,
      "Cumulative Figures (On+Off Campus) out of Eligible": 12,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 67,
      "Students Opted for Higher Studies": 19,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 48,
      "Students Eligible for Placement": 42,
      "Students Not-Eligible for Placement": 6,
      "% of Placement out of Interested Students in Placement": 0.25,
      "% of Placement out of Eligible students  for Placement": 0.2857142857142857,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 2,
      "Maximum Salary( INR- LPA)": 5.6,
      "Minimum Salary ( INR- LPA)": 3.2,
      "Average Salary ( INR- LPA)": 3.983333333333334,
      "Median Salary (INR-LPA)": 3.675,
      "Mode Salary (INR-LPA)": 3.6,
      "No of Companies Visited": 84,
    },
    {
      "Placement Statistics ": "MME",
      "Total Offers ": 17,
      "Total Single Offers (On Campus)": 6,
      "Off-Campus Offers": 9,
      "Cumulative Figures (On+Off Campus) out of Interested": 15,
      "Cumulative Figures (On+Off Campus) out of Eligible": 13,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 2,
      "Students Admitted in Final Year": 63,
      "Students Opted for Higher Studies": 31,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 31,
      "Students Eligible for Placement": 27,
      "Students Not-Eligible for Placement": 4,
      "% of Placement out of Interested Students in Placement": 0.4838709677419355,
      "% of Placement out of Eligible students  for Placement": 0.4814814814814815,
      "%  of Placement out of Not-Eligible students for Placement": 0.5,
      "No of Super Dream/Dream": 7,
      "Maximum Salary( INR- LPA)": 6.5,
      "Minimum Salary ( INR- LPA)": 3.6,
      "Average Salary ( INR- LPA)": 4.918666666666667,
      "Median Salary (INR-LPA)": 4.8,
      "Mode Salary (INR-LPA)": 6.5,
      "No of Companies Visited": 78,
    },
    {
      "Placement Statistics ": "CIVIL",
      "Total Offers ": 13,
      "Total Single Offers (On Campus)": 12,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 13,
      "Cumulative Figures (On+Off Campus) out of Eligible": 13,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 67,
      "Students Opted for Higher Studies": 34,
      "Students Opted for  Entrepreneur": 4,
      "Students Interested in Placement": 29,
      "Students Eligible for Placement": 22,
      "Students Not-Eligible for Placement": 7,
      "% of Placement out of Interested Students in Placement": 0.4482758620689655,
      "% of Placement out of Eligible students  for Placement": 0.5909090909090909,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 0,
      "Maximum Salary( INR- LPA)": 4,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 3.265384615384616,
      "Median Salary (INR-LPA)": 3,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 64,
    },
    {
      "Placement Statistics ": "Total ",
      "Total Offers ": 379,
      "Total Single Offers (On Campus)": 305,
      "Off-Campus Offers": 20,
      "Cumulative Figures (On+Off Campus) out of Interested": 325,
      "Cumulative Figures (On+Off Campus) out of Eligible": 323,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 2,
      "Students Admitted in Final Year": 977,
      "Students Opted for Higher Studies": 265,
      "Students Opted for  Entrepreneur": 18,
      "Students Interested in Placement": 694,
      "Students Eligible for Placement": 660,
      "Students Not-Eligible for Placement": 34,
      "% of Placement out of Interested Students in Placement": 0.468299711815562,
      "% of Placement out of Eligible students  for Placement": 0.4893939393939394,
      "%  of Placement out of Not-Eligible students for Placement": 0.05882352941176471,
      "No of Super Dream/Dream": 117,
      "Maximum Salary( INR- LPA)": 40,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.483209876543194,
      "Median Salary (INR-LPA)": 4.25,
      "Mode Salary (INR-LPA)": 3.6,
      "No of Companies Visited": 128,
    },
  ],
};
