export const data2024 = {
  "2024": [
    {
      "Placement Statistics ": "AI&DS",
      "Total Offers ": 49,
      "Total Single Offers (On Campus)": 39,
      "Off-Campus Offers": 5,
      "Cumulative Figures (On+Off Campus) out of Interested": 44,
      "Cumulative Figures (On+Off Campus) out of Eligible": 44,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 70,
      "Students Opted for Higher Studies": 13,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 57,
      "Students Eligible for Placement": 57,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.7719298245614035,
      "% of Placement out of Eligible students  for Placement": 0.7719298245614035,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 21,
      "Maximum Salary( INR- LPA)": 12,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.117045454545454,
      "Median Salary (INR-LPA)": 4.375,
      "Mode Salary (INR-LPA)": 4,
      "No of Companies Visited": 151,
    },
    {
      "Placement Statistics ": "AI&ML",
      "Total Offers ": 51,
      "Total Single Offers (On Campus)": 37,
      "Off-Campus Offers": 8,
      "Cumulative Figures (On+Off Campus) out of Interested": 45,
      "Cumulative Figures (On+Off Campus) out of Eligible": 45,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 69,
      "Students Opted for Higher Studies": 10,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 59,
      "Students Eligible for Placement": 59,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.7627118644067796,
      "% of Placement out of Eligible students  for Placement": 0.7627118644067796,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 22,
      "Maximum Salary( INR- LPA)": 40,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 6.16088888888889,
      "Median Salary (INR-LPA)": 4.5,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 151,
    },
    {
      "Placement Statistics ": "IoT",
      "Total Offers ": 20,
      "Total Single Offers (On Campus)": 16,
      "Off-Campus Offers": 2,
      "Cumulative Figures (On+Off Campus) out of Interested": 18,
      "Cumulative Figures (On+Off Campus) out of Eligible": 18,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 33,
      "Students Opted for Higher Studies": 8,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 25,
      "Students Eligible for Placement": 25,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.72,
      "% of Placement out of Eligible students  for Placement": 0.72,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 4,
      "Maximum Salary( INR- LPA)": 9,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.451666666666666,
      "Median Salary (INR-LPA)": 4.1,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 151,
    },
    {
      "Placement Statistics ": "COMP",
      "Total Offers ": 157,
      "Total Single Offers (On Campus)": 125,
      "Off-Campus Offers": 8,
      "Cumulative Figures (On+Off Campus) out of Interested": 133,
      "Cumulative Figures (On+Off Campus) out of Eligible": 133,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 208,
      "Students Opted for Higher Studies": 43,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 162,
      "Students Eligible for Placement": 162,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.8209876543209876,
      "% of Placement out of Eligible students  for Placement": 0.8209876543209876,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 81,
      "Maximum Salary( INR- LPA)": 19.75,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 6.526390977443612,
      "Median Salary (INR-LPA)": 5.2,
      "Mode Salary (INR-LPA)": 4.25,
      "No of Companies Visited": 160,
    },
    {
      "Placement Statistics ": "ELEX",
      "Total Offers ": 27,
      "Total Single Offers (On Campus)": 18,
      "Off-Campus Offers": 6,
      "Cumulative Figures (On+Off Campus) out of Interested": 24,
      "Cumulative Figures (On+Off Campus) out of Eligible": 24,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 64,
      "Students Opted for Higher Studies": 20,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 44,
      "Students Eligible for Placement": 41,
      "Students Not-Eligible for Placement": 3,
      "% of Placement out of Interested Students in Placement": 0.5454545454545454,
      "% of Placement out of Eligible students  for Placement": 0.5853658536585366,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 5,
      "Maximum Salary( INR- LPA)": 10.2,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 4.20625,
      "Median Salary (INR-LPA)": 4,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 156,
    },
    {
      "Placement Statistics ": "E&TC",
      "Total Offers ": 75,
      "Total Single Offers (On Campus)": 58,
      "Off-Campus Offers": 8,
      "Cumulative Figures (On+Off Campus) out of Interested": 66,
      "Cumulative Figures (On+Off Campus) out of Eligible": 66,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 135,
      "Students Opted for Higher Studies": 33,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 101,
      "Students Eligible for Placement": 101,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.6534653465346535,
      "% of Placement out of Eligible students  for Placement": 0.6534653465346535,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 21,
      "Maximum Salary( INR- LPA)": 19.75,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.030909090909092,
      "Median Salary (INR-LPA)": 4.25,
      "Mode Salary (INR-LPA)": 4.25,
      "No of Companies Visited": 155,
    },
    {
      "Placement Statistics ": "IT",
      "Total Offers ": 90,
      "Total Single Offers (On Campus)": 68,
      "Off-Campus Offers": 8,
      "Cumulative Figures (On+Off Campus) out of Interested": 76,
      "Cumulative Figures (On+Off Campus) out of Eligible": 76,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 139,
      "Students Opted for Higher Studies": 37,
      "Students Opted for  Entrepreneur": 0,
      "Students Interested in Placement": 99,
      "Students Eligible for Placement": 99,
      "Students Not-Eligible for Placement": 0,
      "% of Placement out of Interested Students in Placement": 0.7676767676767676,
      "% of Placement out of Eligible students  for Placement": 0.7676767676767676,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 44,
      "Maximum Salary( INR- LPA)": 19.75,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.812236842105264,
      "Median Salary (INR-LPA)": 5.15,
      "Mode Salary (INR-LPA)": 4,
      "No of Companies Visited": 160,
    },
    {
      "Placement Statistics ": "Mech",
      "Total Offers ": 54,
      "Total Single Offers (On Campus)": 45,
      "Off-Campus Offers": 2,
      "Cumulative Figures (On+Off Campus) out of Interested": 47,
      "Cumulative Figures (On+Off Campus) out of Eligible": 47,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 132,
      "Students Opted for Higher Studies": 54,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 77,
      "Students Eligible for Placement": 69,
      "Students Not-Eligible for Placement": 8,
      "% of Placement out of Interested Students in Placement": 0.6103896103896104,
      "% of Placement out of Eligible students  for Placement": 0.6811594202898551,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 8,
      "Maximum Salary( INR- LPA)": 7.5,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 3.839999999999999,
      "Median Salary (INR-LPA)": 3.25,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 141,
    },
    {
      "Placement Statistics ": "CIVIL",
      "Total Offers ": 45,
      "Total Single Offers (On Campus)": 35,
      "Off-Campus Offers": 8,
      "Cumulative Figures (On+Off Campus) out of Interested": 43,
      "Cumulative Figures (On+Off Campus) out of Eligible": 43,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 137,
      "Students Opted for Higher Studies": 59,
      "Students Opted for  Entrepreneur": 9,
      "Students Interested in Placement": 69,
      "Students Eligible for Placement": 65,
      "Students Not-Eligible for Placement": 4,
      "% of Placement out of Interested Students in Placement": 0.6231884057971014,
      "% of Placement out of Eligible students  for Placement": 0.6615384615384615,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 0,
      "Maximum Salary( INR- LPA)": 4.5,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 3.274418604651163,
      "Median Salary (INR-LPA)": 3,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 117,
    },
    {
      "Placement Statistics ": "Total ",
      "Total Offers ": 568,
      "Total Single Offers (On Campus)": 441,
      "Off-Campus Offers": 55,
      "Cumulative Figures (On+Off Campus) out of Interested": 496,
      "Cumulative Figures (On+Off Campus) out of Eligible": 496,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 987,
      "Students Opted for Higher Studies": 277,
      "Students Opted for  Entrepreneur": 17,
      "Students Interested in Placement": 693,
      "Students Eligible for Placement": 678,
      "Students Not-Eligible for Placement": 15,
      "% of Placement out of Interested Students in Placement": 0.7157287157287158,
      "% of Placement out of Eligible students  for Placement": 0.7315634218289085,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 206,
      "Maximum Salary( INR- LPA)": 40,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.20530973451327,
      "Median Salary (INR-LPA)": 4.25,
      "Mode Salary (INR-LPA)": 3,
      "No of Companies Visited": 244,
    },
  ],
};
