# Generated by Django 5.1.1 on 2024-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('batch', models.CharField(max_length=255)),
                ('present', models.CharField(max_length=50)),
                ('late', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
