# Generated by Django 5.1.1 on 2024-12-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_coordinator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
