# Generated by Django 5.1.1 on 2024-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.FloatField(null=True),
        ),
    ]
