# Generated by Django 5.1.1 on 2025-10-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_is_backlog_student_is_kt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_backLog',
            new_name='is_blacklisted',
        ),
    ]
