# Generated by Django 5.1.1 on 2025-04-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_is_backlog_student_is_kt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='consent',
            field=models.CharField(choices=[('placement', 'placement'), ('Higher studies', 'Higher studies'), ('Entrepreneurship', 'Entrepreneurship')], default='placement', max_length=30),
        ),
    ]
