# Generated by Django 5.1.1 on 2025-10-08 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0006_rename_is_backlog_student_is_blacklisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_student_coordinator',
            new_name='joined_company',
        ),
        migrations.CreateModel(
            name='StudentOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[('PLACEMENT', 'Placement'), ('AEDP_PLI', 'AEDP/PLI'), ('AEDP_OJT', 'AEDP/OJT')], default='PLACEMENT', max_length=20)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('joined', 'Joined')], default='offered', max_length=20)),
                ('salary', models.FloatField()),
                ('role', models.CharField(max_length=255)),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('is_aedp_pli', models.BooleanField(default=False)),
                ('is_aedp_ojt', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_offers', to='staff.companyregistration')),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_offers', to='staff.joboffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_offers', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'company', 'role')},
            },
        ),
    ]
