# Generated by Django 5.1.1 on 2025-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_pli',
            field=models.BooleanField(default=False),
        ),
    ]
