# Generated by Django 5.1.1 on 2025-10-18 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0007_rename_is_student_coordinator_student_joined_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card',
            field=models.CharField(choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='consent',
            field=models.CharField(choices=[('placement', 'placement'), ('placement+aedp/pli', 'placement+aedp/pli'), ('Higher studies', 'Higher studies')], default='placement', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentPlacementAppliedCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interested', models.BooleanField(default=False)),
                ('not_interested_reason', models.TextField()),
                ('application_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='staff.companyregistration')),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='staff.joboffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_companies', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PlacementCompanyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered', models.BooleanField(default=True)),
                ('aptitude_test', models.BooleanField(default=False)),
                ('technical_interview', models.BooleanField(default=False)),
                ('hr_interview', models.BooleanField(default=False)),
                ('gd', models.BooleanField(default=False)),
                ('final_result', models.CharField(default='Pending', max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='student.studentplacementappliedcompany')),
            ],
        ),
    ]
