# Generated by Django 5.1.1 on 2025-10-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_card_alter_student_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcompanyprogress',
            name='coding_test',
            field=models.BooleanField(default=False),
        ),
    ]
