# Generated by Django 4.2.19 on 2025-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_is_pli'),
        ('student', '0008_alter_student_card_alter_student_consent_and_more'),
    ]

    operations = [
    ]
