# Generated by Django 5.1.1 on 2025-10-23 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_placementcompanyprogress_coding_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_url',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='ActivitiesAndAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_and_achievements', to='student.student')),
            ],
        ),
    ]
