# Generated by Django 4.2.19 on 2025-10-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_merge_20251018_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_pli',
        ),
        migrations.AlterField(
            model_name='student',
            name='consent',
            field=models.CharField(choices=[('placement', 'placement'), ('placement+aedp/pli', 'placement+aedp/pli'), ('Higher studies', 'Higher studies'), ('Entrepreneurship', 'Entrepreneurship')], default='placement', max_length=30),
        ),
    ]
