# Generated by Django 5.1.1 on 2025-10-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_resume_profile_url_activitiesandachievement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitiesAndAchievement',
            new_name='Resume_ActivitiesAndAchievement',
        ),
    ]
