# Generated by Django 5.1.1 on 2025-10-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_activitiesandachievement_resume_activitiesandachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_activitiesandachievement',
            name='student',
        ),
        migrations.AddField(
            model_name='resume_activitiesandachievement',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_and_achievements', to='student.resume'),
        ),
    ]
