# Generated by Django 5.1.1 on 2025-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_resume_activitiesandachievement_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='profile_url',
        ),
        migrations.AddField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
