# Generated by Django 4.2.19 on 2025-10-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_student_is_pli_alter_student_consent'),
        ('student', '0013_remove_resume_profile_url_resume_profile_image'),
    ]

    operations = [
    ]
