# Generated by Django 5.1.1 on 2025-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_merge_20251024_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingperformancesemester',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trainingperformancesemester',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.DeleteModel(
            name='TrainingAttendanceSemester',
        ),
        migrations.DeleteModel(
            name='TrainingPerformanceSemester',
        ),
    ]
