# Generated by Django 5.1.1 on 2026-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_trainingperformancesemester_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_category',
            field=models.CharField(choices=[('Category 1', 'category 1'), ('Category 2', 'category 2'), ('Category 3', 'category 3'), ('No category', 'No category')], db_index=True, default='No category', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
