# Generated by Django 5.1.1 on 2026-08-10 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_repoint_placement_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentoffer',
            name='offer_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
