# Generated by Django 5.1.1 on 2026-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_passkeychallenge_passkeycredential_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passkeycredential',
            name='credential_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
