export const data2023 = {
  "2023": [
    {
      "Placement Statistics ": "COMP",
      "Total Offers ": 193,
      "Total Single Offers (On Campus)": 128,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 129,
      "Cumulative Figures (On+Off Campus) out of Eligible": 129,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 212,
      "Students Opted for Higher Studies": 68,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 141,
      "Students Eligible for Placement": 137,
      "Students Not-Eligible for Placement": 4,
      "% of Placement out of Interested Students in Placement": 0.9148936170212766,
      "% of Placement out of Eligible students  for Placement": 0.9416058394160584,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 106,
      "Maximum Salary( INR- LPA)": 0,
      "Minimum Salary ( INR- LPA)": 0,
      "Average Salary ( INR- LPA)": 6.662365591397848,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 112,
    },
    {
      "Placement Statistics ": "ELEX",
      "Total Offers ": 41,
      "Total Single Offers (On Campus)": 36,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 36,
      "Cumulative Figures (On+Off Campus) out of Eligible": 36,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 71,
      "Students Opted for Higher Studies": 17,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 53,
      "Students Eligible for Placement": 52,
      "Students Not-Eligible for Placement": 1,
      "% of Placement out of Interested Students in Placement": 0.679245283018868,
      "% of Placement out of Eligible students  for Placement": 0.6923076923076923,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 14,
      "Maximum Salary( INR- LPA)": 0,
      "Minimum Salary ( INR- LPA)": 0,
      "Average Salary ( INR- LPA)": 4.481627906976745,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 103,
    },
    {
      "Placement Statistics ": "E&TC",
      "Total Offers ": 112,
      "Total Single Offers (On Campus)": 87,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 87,
      "Cumulative Figures (On+Off Campus) out of Eligible": 87,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 137,
      "Students Opted for Higher Studies": 28,
      "Students Opted for  Entrepreneur": 1,
      "Students Interested in Placement": 108,
      "Students Eligible for Placement": 102,
      "Students Not-Eligible for Placement": 6,
      "% of Placement out of Interested Students in Placement": 0.8055555555555556,
      "% of Placement out of Eligible students  for Placement": 0.8529411764705882,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 36,
      "Maximum Salary( INR- LPA)": 0,
      "Minimum Salary ( INR- LPA)": 0,
      "Average Salary ( INR- LPA)": 4.74451612903226,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 103,
    },
    {
      "Placement Statistics ": "IT",
      "Total Offers ": 112,
      "Total Single Offers (On Campus)": 85,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 85,
      "Cumulative Figures (On+Off Campus) out of Eligible": 85,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 141,
      "Students Opted for Higher Studies": 35,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 103,
      "Students Eligible for Placement": 100,
      "Students Not-Eligible for Placement": 3,
      "% of Placement out of Interested Students in Placement": 0.8252427184466019,
      "% of Placement out of Eligible students  for Placement": 0.85,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 68,
      "Maximum Salary( INR- LPA)": 0,
      "Minimum Salary ( INR- LPA)": 0,
      "Average Salary ( INR- LPA)": 6.22255813953488,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 112,
    },
    {
      "Placement Statistics ": "Mech",
      "Total Offers ": 25,
      "Total Single Offers (On Campus)": 25,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 25,
      "Cumulative Figures (On+Off Campus) out of Eligible": 25,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 139,
      "Students Opted for Higher Studies": 55,
      "Students Opted for  Entrepreneur": 3,
      "Students Interested in Placement": 81,
      "Students Eligible for Placement": 79,
      "Students Not-Eligible for Placement": 2,
      "% of Placement out of Interested Students in Placement": 0.308641975308642,
      "% of Placement out of Eligible students  for Placement": 0.3164556962025317,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 5,
      "Maximum Salary( INR- LPA)": 0,
      "Minimum Salary ( INR- LPA)": 0,
      "Average Salary ( INR- LPA)": 4.201621621621623,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 65,
    },
    {
      "Placement Statistics ": "CIVIL",
      "Total Offers ": 6,
      "Total Single Offers (On Campus)": 6,
      "Off-Campus Offers": 0,
      "Cumulative Figures (On+Off Campus) out of Interested": 6,
      "Cumulative Figures (On+Off Campus) out of Eligible": 6,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 152,
      "Students Opted for Higher Studies": 95,
      "Students Opted for  Entrepreneur": 2,
      "Students Interested in Placement": 55,
      "Students Eligible for Placement": 48,
      "Students Not-Eligible for Placement": 7,
      "% of Placement out of Interested Students in Placement": 0.1090909090909091,
      "% of Placement out of Eligible students  for Placement": 0.125,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 1,
      "Maximum Salary( INR- LPA)": 0,
      "Minimum Salary ( INR- LPA)": 0,
      "Average Salary ( INR- LPA)": 3.758095238095238,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 50,
    },
    {
      "Placement Statistics ": "Total ",
      "Total Offers ": 489,
      "Total Single Offers (On Campus)": 367,
      "Off-Campus Offers": 1,
      "Cumulative Figures (On+Off Campus) out of Interested": 368,
      "Cumulative Figures (On+Off Campus) out of Eligible": 368,
      "Cumulative Figures (On+Off Campus) out of  Not Eligible ": 0,
      "Students Admitted in Final Year": 852,
      "Students Opted for Higher Studies": 298,
      "Students Opted for  Entrepreneur": 13,
      "Students Interested in Placement": 541,
      "Students Eligible for Placement": 518,
      "Students Not-Eligible for Placement": 23,
      "% of Placement out of Interested Students in Placement": 0.6802218114602587,
      "% of Placement out of Eligible students  for Placement": 0.7104247104247104,
      "%  of Placement out of Not-Eligible students for Placement": 0,
      "No of Super Dream/Dream": 230,
      "Maximum Salary( INR- LPA)": 3,
      "Minimum Salary ( INR- LPA)": 3,
      "Average Salary ( INR- LPA)": 5.423780160857905,
      "Median Salary (INR-LPA)": 0,
      "Mode Salary (INR-LPA)": 0,
      "No of Companies Visited": 134,
    },
  ],
};
