# Generated by Django 5.1.1 on 2024-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipregistration',
            name='batch',
            field=models.CharField(default='2026', max_length=100),
        ),
    ]
