# Generated by Django 5.1.1 on 2025-11-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_api', '0004_remove_internshipacceptance_position_and_more'),
        ('student', '0015_alter_trainingperformancesemester_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipacceptance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internship_offer_acceptance', to='student.student'),
        ),
    ]
