# Generated by Django 5.1.1 on 2026-08-05 11:09

import base.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_api', '0005_alter_internshipacceptance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipacceptance',
            name='offer_letter',
            field=models.FileField(upload_to='offer_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), base.upload_validators.MaxFileSizeValidator(10)]),
        ),
    ]
