# Generated by Django 5.1.1 on 2025-09-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
