# Generated by Django 4.2.19 on 2025-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type_notification'),
        ('notifications', '0003_notification_link'),
    ]

    operations = [
    ]
