# Generated by Django 4.2.19 on 2025-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20251018_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
