# Generated by Django 5.1.1 on 2026-07-18 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('training', 'Training'), ('placement', 'Placement'), ('internship', 'Internship'), ('resource', 'Resource')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_academic_years',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('all_students', 'All Students'), ('all_faculty', 'All Faculty'), ('all_staff', 'All Staff'), ('all_placement_officers', 'All Placement Officers'), ('all_training_officers', 'All Training Officers'), ('all_internship_officers', 'All Internship Officers'), ('department_students', 'Department-specific Students'), ('year_students', 'Year-specific Students'), ('department_faculty', 'Department-specific Faculty'), ('all_users', 'All Users')], default='all_students', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
