# Generated by Django 5.1.1 on 2026-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_type_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('training', 'Training'), ('placement', 'Placement'), ('internship', 'Internship'), ('resource', 'Resource')], db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('all_students', 'All Students'), ('all_faculty', 'All Faculty'), ('all_staff', 'All Staff'), ('all_placement_officers', 'All Placement Officers'), ('all_training_officers', 'All Training Officers'), ('all_internship_officers', 'All Internship Officers'), ('department_students', 'Department-specific Students'), ('year_students', 'Year-specific Students'), ('department_faculty', 'Department-specific Faculty'), ('all_users', 'All Users')], db_index=True, default='all_students', max_length=50),
        ),
    ]
