# Generated by Django 5.1.1 on 2026-08-05 11:09

import base.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='notifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'txt', 'csv']), base.upload_validators.MaxFileSizeValidator(10)]),
        ),
    ]
